# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a0f4006d30b7b8b39c63ef9b0ad5e69818a87e5eaa9da38a8d8dcadb91df17f4ffe4db11fa0a72e1a4e222563ebf7bb37da002dd119e79428a9b0e3962b767

test:
  secret_key_base: 1d639682fefaeb7f26ef02665e10db81351d62702f5fa7f62ac498114b84e6d45eb154dc52ea465fb9e08526949f63ad4b3fa432fbf44540ec08ff2be619a64a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
